### ISSUE TITLE
How to select gpu device?

### ISSUE THREAD

**Issue by lliuz** [FORTH-ModelBasedTracker/PyOpenPose#12]
First of all thanks for the project. I just found that it always uses "gpu 0", and I'd like to use multiple gpus to speed up inference, or I want to create multiple objects to use different gpu. It seems useful to me but I am not familiar with how to modify the code to add this feature..

**Comment by padeler** [comment]
In the latest commit I added an option to the wrapper to pass the desired gpuId to the openpose library. This is a temporary fix. I plan to make a refactoring that will allow more flexibility when setting parameters for the 3 networks (pose, face, hand).

**Comment by lliuz** [comment]
Thanks for the answer, and nice to know that this feature will be available.
