### ISSUE TITLE
MAKE ERROR

### ISSUE THREAD

**Issue by derekwong66** [FORTH-ModelBasedTracker/PyOpenPose#14]
[ 25%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o
[ 50%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/PyOpenPose.cpp.o
[ 75%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o
[100%] Linking CXX shared library PyOpenPose.so
/usr/bin/ld: cannot find -lopenpose
/usr/bin/ld: cannot find -lcaffe
collect2: error: ld returned 1 exit status
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:194: recipe for target 'PyOpenPoseLib/PyOpenPose.so' failed
make[2]: *** [PyOpenPoseLib/PyOpenPose.so] Error 1
CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by padeler** [comment]
Did you set the OPENPOSE_ROOT variable to point to the openpose root folder?

Note that the build script assumes that you use the Makefile (make distribute) to build openpose. If you choose to install the libraries else where, you must adapt CMakeLists.txt accordingly.

**Comment by derekwong66** [comment]
@padeler  I have set OPENPSOE_ROOT
I can run openpose demo, I used cmake to build openpose.
How to modifiy CMakeLists.txt?

**Comment by padeler** [comment]
You have to set the correct paths for caffe and openpose libs and header folders in lines [59-62](https://github.com/FORTH-ModelBasedTracker/PyOpenPose/blob/master/CMakeLists.txt#L59).

**Comment by unrealwill** [comment]
Hello, I've encountered the same problem, but I've solved it by installing openpose with : 
sudo make install from openpose/build as described in the section :
OpenPose from other Projects of documentation
 https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_cmake.md

**Comment by derekwong66** [comment]
@unrealwill you are right. I can make it now. However, when I  try to run scripts/JusthandNet.py, Importing PyOpenPose as op failed.

**Comment by padeler** [comment]
Did you find a solution to your issue?

**Comment by unrealwill** [comment]
Nope, but I got around my problem by writing a c++ zmq server which uses OpenPose and serve the info I need.

**Comment by padeler** [comment]
ok so I am closing this issue.

**Comment by unrealwill** [comment]
@padeler I'm not the OP, so I don't know if he solved his issue one way or another.
@derekwong66 You can look at my project https://github.com/GistNoesis/Linn-Photobooth for the zmq server and usage

**Comment by padeler** [comment]
I have not tried pyopenpose with python3. I'll test it when i have some time, and report here for future reference.

**Comment by HibikiKai** [comment]
https://github.com/FORTH-ModelBasedTracker/PyOpenPose/issues/29
