### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by unrealwill** [FORTH-ModelBasedTracker/PyOpenPose#15]
Hello,

Couldn't get PyOpenPose to be imported in python3

I corrected one mistake : it was linking against boost-python-2.7 
So in CMakeLists.txt I modified : 
find_package(Boost COMPONENTS system "python" REQUIRED)
find_package(Boost COMPONENTS system "python-py35" REQUIRED)

Compilation works fine but upon importing though it seems to be going further but now I encounter an error which doesn't give any search result :
import PyOpenPose
ImportError: /home/username/PyOpenPose/build/PyOpenPoseLib/PyOpenPose.so: undefined symbol: _ZN2op18FaceExtractorCaffeC1ERKNS_5PointIiEES4_RKSsiRKSt6vectorINS_11HeatMapTypeESaIS8_EENS_9ScaleModeEb

I checked out commit of openPose e086e6fc6a5f4650d5c3a100b8ced8363fd2d099 (which is the number you indicate) which was compiled successfully with cmake and then installed with make install

Thank you for your help

**Comment by sandromario** [comment]
Any update on this?

**Comment by unrealwill** [comment]
@sandromario I solved my use case by making a zmq server in c++ which receive image and return poses to python. You can have a look at it on https://github.com/GistNoesis/Linn-Photobooth openpose/examples for the c++ part. And pose.py for the python side.
It's not actively maintained to be kept in sync with last Openpose version but it should need less maintenance that PyOpenPose, as it's just a wrapper of some tutorial code.

**Comment by padeler** [comment]
Hello,

I found some time to test PyOpenPose with python3. It works ok on my setup. 
The only changes on the code was the adaptation for the example scripts to python3 (i.e print syntax). These are already committed.

For compiling with python3 you need:
1. You have to make sure that the cmake discovers python3 and sets the PYTHON_INCLUDE_DIR and PYTHON_LIBRARY variables to the correct python3 values (and easy way to check this is to use cmake-gui).
2. Make sure that 
 `/usr/lib/x86_64-linux-gnu/libboost_python.so`

points to the python3 library: 
`/usr/lib/x86_64-linux-gnu/libboost_python-py35.so`

and **not** to python 2.7:
` /usr/lib/x86_64-linux-gnu/libboost_python-py27.so`

Compile the library and run the scripts with python3.

Tested on ubuntu 16.04  and python 3.5.2

**Comment by sandromario** [comment]
Thanks, that's much appreciated. It's working now. Put the following in your `CMakeLists.txt` (replacing the existing versions of those lines):

`find_package(Boost COMPONENTS system python-py35 REQUIRED)
find_package(PythonLibs 3 REQUIRED)`

And then run `cmake ..` using:

`cmake -DPYTHON_INCLUDE_DIR=/opt/conda/include/python3.6m/ -DPYTHON_LIBRARY=/opt/conda/lib/libpython3.6m.so ..`

...assuming you're using a Conda setup living in `/opt/conda` (obviously, change the path accordingly if not).

**Comment by padeler** [comment]
I think this solves it, thanks @sandromario, I will close this issue now.
