### ISSUE TITLE
Are persons returned in the pose, face and hands objects in the same order?

### ISSUE THREAD

**Issue by sandromario** [FORTH-ModelBasedTracker/PyOpenPose#17]
I am running PyOpenPose to obtain pose, face and hand keypoints for one and the same image.

I can't seem to find any explanation as to whether the persons in the persons, faces and hands objects (see code below) are guaranteed to be in the same order. PyOpenPose is running three separate commands, so it would be helpful to know that the order of the persons is the same in the pose, hands and face objects.

`
op.detectPose(image_arr)
poses = self.op.getKeypoints(op.KeypointType.POSE)[0]
op.detectFace(image_arr)
faces = op.getKeypoints(op.KeypointType.FACE)[0]
op.detectHands(image_arr)
hands = op.getKeypoints(op.KeypointType.HAND)[0]
`

It would be great if this could be documented somewhere.

**Comment by padeler** [comment]
Yes it is the same. 

Note however that in different frames openpose might detect people with different order so you cannot rely on the idx of the person for tracking.

**Comment by afrizalfi** [comment]
Hi.
how to get the coordinate of each person? i want to put the text at each person.

**Comment by padeler** [comment]
each person is returned as a number of joints (in the same order/indexing as openpose). Each joint is 3 numbers (x,y,p). You can use the x,y image coordinates to draw text to the location of any joint you want.

**Comment by afrizalfi** [comment]
Ok Thank You for the answer. is p mean probability?

**Comment by padeler** [comment]
p is the confidence of openpose for the given joint location.
