### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by afrizalfi** [FORTH-ModelBasedTracker/PyOpenPose#18]
Hi, i just get the following error "Segmentation fault (core dumped)" when i run the example code in "script" folder. 
I change the syntax "cap = cv2.VideoCapture(0)" to "cap = cv2.VideoCapture('video.avi')" because my server didnt connect to webcam so i want to run video from file. All example code get the same error "Segmentation fault (core dumped)"

I am using python 2.7, opencv 3.3.0, linux Ubuntu 14.04.5

What should i do?

**Comment by padeler** [comment]
Hello,

Can you be a bit more specific on the location of the segfault? 
On which line on the script do you get it?

**Comment by afrizalfi** [comment]
I run JustFaceNet.py

When i put "import cv2" above "import PyOpenPose as OP", the error happen in syntax "ret, frame = cap.read()" in line 40
The output error just like this :
Segmentation fault (core dumped)

But when i put "import PyOpenPose as OP" above "import cv2", the error happen in "op.detectFace(rgb, np.array(faceBB, dtype=np.int32).reshape((1, 4)))" in line 69
The output error like this :
('Net output size: ', [1280, 720])
/home/dependencies/pyopenpose2/PyOpenPose/PyOpenPoseLib/OpenPoseWrapper.cpp:OpenPoseWrapper():83
Starting initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():173
Finished initialization on thread. In src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():188
Starting initialization on thread. In src/openpose/pose/poseGpuRenderer.cpp:initializationOnThread():48
Finished initialization on thread. In src/openpose/pose/poseGpuRenderer.cpp:initializationOnThread():55
Starting initialization on thread. In src/openpose/face/faceExtractorCaffe.cpp:netInitializationOnThread():134
Finished initialization on thread. In src/openpose/face/faceExtractorCaffe.cpp:netInitializationOnThread():144
Starting initialization on thread. In src/openpose/face/faceGpuRenderer.cpp:initializationOnThread():36
Finished initialization on thread. In src/openpose/face/faceGpuRenderer.cpp:initializationOnThread():41
Entering main Loop. Put your hand into the box to start tracking
Segmentation fault (core dumped)

I think opencv and PyOpenPose clashed but i dont have idea why this happen.

**Comment by padeler** [comment]
The first error indicates an issue with opencv. Can you run opencv only scripts normally (for example if you just read from a video file and show the images in a loop) ?

**Comment by afrizalfi** [comment]
Yes i can run opencv normally like read image and read video from file and output it with cv2.imshow and cv2.waitKey. cv2.imwrite is also work.
 
Actually, before i install the opencv 3.3.0, i have opencv 2.4 in my server. And i build and make install opencv 3.3.0 from https://github.com/BVLC/caffe/wiki/OpenCV-3.3-Installation-Guide-on-Ubuntu-16.04 **without** uninstall or remove the old opencv. I just replace the cv2.so in '/usr/local/lib/python2.7/dist-packages/cv2.so'. Is that a problem?

**Comment by padeler** [comment]
Replacing libraries instead of doing a proper install is never a good idea and can lead to all sorts of strange issues. I would try to do a clean install of opencv and the rest of the dependencies and then rebuild openpose and pyopenpose making sure that the build systems use the correct headers and libraries.

**Comment by afrizalfi** [comment]
It works. I clean opencv and re install it. and then rebuild openpose and pyopenpose and it works.
Thank you very much :+1: . This issue is solved and closed
