### ISSUE TITLE
Cmake build error

### ISSUE THREAD

**Issue by lyzband** [FORTH-ModelBasedTracker/PyOpenPose#19]
Hello there,
I've been trying to build this with cmake but i keep getting the same error message.

![cmake-gui](https://user-images.githubusercontent.com/31686617/34600897-11ecf02a-f23d-11e7-8e9b-9e0732b9a98c.png)
this is what i can see from cmake-gui after following the solution from #15 and also setting OPENPOSE_ROOT properly.

but everytime I tried to build with cmake, the following is the error i got.

> make
Scanning dependencies of target PyOpenPose
[ 25%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o
[ 50%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/PyOpenPose.cpp.o
[ 75%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o
/home/sjoh/Projects/PyOpenPose-master/PyOpenPoseLib/opencv_expose.cpp:13:33: fatal error: numpy/ndarrayobject.h: No such file or directory
compilation terminated.
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:110: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o' failed
make[2]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Apparently I can find the 'ndarrayobject.h' file in '/usr/local/lib/python3.5/dist-packages/numpy/core/include/numpy/ndarrayobject.h'

is there anything i got to edit? if so, could you please tell me how?

**Comment by lyzband** [comment]
but i already installed numpy for python3 and it can be imported without any problems

**Comment by padeler** [comment]
The latest commit should make it easier to choose python version by adapting the CMakeLists.txt file.
