### ISSUE TITLE
libprotobuf error google/protobuf/descriptor_database.cc:57 file already exists in database: caffe.proto

### ISSUE THREAD

**Issue by hub111** [FORTH-ModelBasedTracker/PyOpenPose#2]
I build the PyOpenPose successfully, but when I run the test file OpLoop.py, I get this error. Could you give some advises to fix it? Thank you.

**Comment by padeler** [comment]
This looks like an openpose issue, it is not related to PyOpenPose. Do you have the latest openpose version checked-out? Do the openpose examples work?

**Comment by hub111** [comment]
Yes, I check my openpose and find that it doesn't work after I change the opencv2.4 to opencv 3.3. I change the version of opencv, because I found that pyopenpose need opencv 3.3. I guess the problem is caused by the version of opencv. Can you tell me which version of opencv and protobuf you use to build openpose?

**Comment by padeler** [comment]
I am using opencv 3.2 and it has been tested with 3.1 as well. I guess 3.3 should work as well. The protobuf version i use is 2.6.1 (from the ubuntu 16.04 repos).

**Comment by hub111** [comment]
Thanks for your reply. After using the configuration you use, I have built the pyopenpose successfully. Thank you so much!

**Comment by filipetrocadoferreira** [comment]
I'm facing the same error. I'm using Opencv 3.2

**Comment by filipetrocadoferreira** [comment]
After doing this : https://xiaobai1217.github.io/2017/08/07/fast_rcnn/#more

I know face a SegFault during import
