### ISSUE TITLE
How to add python 2 support

### ISSUE THREAD

**Issue by xiaofeiwu** [FORTH-ModelBasedTracker/PyOpenPose#21]
I compiled the code through python 3.4 and it works fine. However, my other codes are python 2.7 and I want to put them together. How to change the code to add python 2.7 support?

Thanks,

**Comment by padeler** [comment]
Hello, 

You just need to configure cmake (i.e using cmake-gui) to python2 instead of python3.

**Comment by xiaofeiwu** [comment]
I found the solution from: https://github.com/djangogo/PyOpenPose, where python version is given by: 
cmake ..  -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so

Thank you all,
Xiaofei
