### ISSUE TITLE
OpenPoseWrapper.cpp:272:60: error: ‘class op::PoseExtractorCaffe’ has no member named ‘getHeatMaps’

### ISSUE THREAD

**Issue by AlexLuya** [FORTH-ModelBasedTracker/PyOpenPose#22]
I got this error when build against openpose  v1.2.1-1.

**Comment by padeler** [comment]
The last tested version of open pose is [1b0325e](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/1b0325e2980a43ba2c9612068f78eb1c38d41ee5). 

In the next few days I will push updates that will bring PyOpenPose up to speed with the latest Openpose commit.  Until then you can checkout the above commit and use it with PyOpenPose.

**Comment by AlexLuya** [comment]
Thanks very much

**Comment by padeler** [comment]
fixed with the latest commit.
