### ISSUE TITLE
Error when try to make PyOpenPose

### ISSUE THREAD

**Issue by HibikiKai** [FORTH-ModelBasedTracker/PyOpenPose#29]
Scanning dependencies of target PyOpenPose
[ 25%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o
[ 50%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/PyOpenPose.cpp.o
[ 75%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o
[100%] Linking CXX shared library PyOpenPose.so
/usr/bin/ld: cannot find -lopenpose
/usr/bin/ld: cannot find -lcaffe
collect2: error: ld returned 1 exit status
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:202: recipe for target 'PyOpenPoseLib/PyOpenPose.so' failed
make[2]: *** [PyOpenPoseLib/PyOpenPose.so] Error 1
CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Thanks in advance

**Comment by HibikiKai** [comment]
Sloved by copying files under openpose/3rdparty/caffe/distribute/lib and openpose/distribute/lib to /usr/lib

**Comment by Axe--** [comment]
@HibikiKai 
Thanks, for me it was the openpose/3rdparty/caffe/distribute/lib & openpose/build/lib

**Comment by Gjain234** [comment]
Basically you need to make sure the libcaffe.so and libopenpose.so files are in /usr/lib so they might be in different places in your project configuration
