### ISSUE TITLE
Big pose detection time difference between same thread and differ thread

### ISSUE THREAD

**Issue by AlexLuya** [FORTH-ModelBasedTracker/PyOpenPose#30]
I want to initialize openpose as  a field of a  RPC server class,and this server will pass all detection requests to this field,the python implementation like this:
(I actually modified some source code of openpose,and described the modification in: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/387)
```
class PosingServer(RPCServer):          
    def test():
            image=cv2.imread("test.png")
            start = time.time() 
            self.net.detectPose(image)
            print "Posing takes {} seconds".format(time.time()  - start) 

    def detect(self, req):#this method to handle RPC request
           self.test()

     def initNetwork(self):
            self.net= OP.OpenPose((656, 368), (240, 240), (640, 480),"COCO", "/pathToModel", 0,False)
            self.test()
```
 As you can see both methods invoke the test() to perform detection on same image,and successfully,but 
```
invoking from initNetwork() takes 13.1403679848 seconds,and it will decrease in follow-up invokings but will stay at 2~3 seconds after 4~5 times

invoking from detect() takes 0.40030002594 seconds
```
**Where does this difference come from?
How to solve this problem?**

**Comment by padeler** [comment]
This is not a PyOpenPose related issue.
That said, I think you are not measuring the actual time it takes to run detectPose(). 
What fps do you achieve with the example script (single threaded) of openpose?

**Comment by AlexLuya** [comment]
@padeler 7~12 fps
What is the reason that you say:"not measuring the actual time it takes to run detectPose()" about blew code?    
```
def test():
            image=cv2.imread("test.png")
            start = time.time() 
            net.detectPose(image)
            print "Posing takes {} seconds".format(time.time()  - start)
```

**Comment by padeler** [comment]
It is because you are also creating a new openpose instance every time you call initNetwork().

**Comment by AlexLuya** [comment]
@padeler ,initNetwork() will be invoked only once,openpose will be saved as instance field,and I have confirmed that the hash id of self.net kept same between different PRC request

**Comment by padeler** [comment]
Closing this issue as it is not related to PyOpenPose runtime.
