### ISSUE TITLE
getHeatMaps error

### ISSUE THREAD

**Issue by winterwater** [FORTH-ModelBasedTracker/PyOpenPose#31]
when I make this project ,something happen as follow,any advices?thanks very much

[ 25%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o
/home/zzy/work/PyOpenPose/PyOpenPoseLib/OpenPoseWrapper.cpp: In member function ‘cv::Mat OpenPoseWrapper::getHeatmaps()’:
/home/zzy/work/PyOpenPose/PyOpenPoseLib/OpenPoseWrapper.cpp:272:60: error: ‘class op::PoseExtractorCaffe’ has no member named ‘getHeatMapsCopy’
 float> maps = membersPtr->poseExtractorCaffe.getHeatMaps
                                              ^
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:62: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o' failed

**Comment by padeler** [comment]
You need to checkout the latest version of openpose (or at least this [commit](https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/d97114f3839770416f115acbce5f38a235421a16)).

**Comment by winterwater** [comment]
I'm tring ,thanks so much
