### ISSUE TITLE
Copy libraries to the system environment

### ISSUE THREAD

**Issue by siqinli** [FORTH-ModelBasedTracker/PyOpenPose#32]
Hi,
I followed  the manual compilation instruction ( https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md ) to install Openpose. I have no idea how to copy headers and libraries to the system environment. Running 'make install' didn't work. Could you please help? Thanks.

**Comment by padeler** [comment]
hello,

If you run ```make distribute``` all the required files (headers and libs) will be copied into a folder named distribute inside openpose root. You must then set OPENPOSE_ROOT environment variable to point to that folder before building PyOpenPose.

**Comment by siqinli** [comment]
@padeler 
Thanks. It works now. But I got an other issue when running the sample codes in "scripts". It throws the error:

Traceback (most recent call last):
  File "OpLoop.py", line 96, in <module>
    run()
  File "OpLoop.py", line 64, in run
    res = op.render(rgb)
KeyboardInterrupt
*** Error in `python': free(): invalid pointer: 0x0000000001491e30 ***
