### ISSUE TITLE
Select GPU

### ISSUE THREAD

**Issue by filipetrocadoferreira** [FORTH-ModelBasedTracker/PyOpenPose#33]
In a multi-GPU environment how to chose which one to use by PyOpenPose?

**Comment by padeler** [comment]
Hello,

The last argument of  the constructor of PyOpenPose is the [gpuid](https://github.com/FORTH-ModelBasedTracker/PyOpenPose/blob/master/PyOpenPoseLib/OpenPoseWrapper.h#L52).
