### ISSUE TITLE
Problem importing PyOpenPose

### ISSUE THREAD

**Issue by svarnypetr** [FORTH-ModelBasedTracker/PyOpenPose#36]
I have:
* OpenPose 1.2.1 (commit 4d3ba29c88608b00c45612052945844aa19be9b4)
* OpenCV 3.4.0
* Python 2.7.12

The OpenPose examples run without any problem. And I am running in a virtualenv in order to keep my OpenCV versions separate.

However, after following the instructions, getting a successful build for OpenPose and PyOpenPose, I get a Bus Error and once segmentation fault when I attempt to import PyOpenPose into python. It does not matter whether I try to run the example scripts or try my own.

Can this be connected to running python in a virtualenv?

**Comment by svarnypetr** [comment]
My bad, I installed openpose using cmake-gui and did not realize I need to run make install.

**Comment by padeler** [comment]
Is the PYTHONPATH and LD_LIBRARY_PATH set to point to the location of the libraries (caffe, openpose pyopenpose)?
