### ISSUE TITLE
Installation failed? ImportError: libopenpose.so.1.2.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joseph-zhong** [FORTH-ModelBasedTracker/PyOpenPose#38]
Hi, after installing OpenPose, Caffe with OpenCV3, and modifying my `$PYTHONPATH`, I get an import error related with OpenPose and not really sure how to resolve

```
~$ echo $PYTHONPATH
/usr/local/PyOpenPose/build/PyOpenPoseLib:......
$ echo $OPENPOSE_ROOT
/usr/local/openpose
```

```
~$ python -c 'import PyOpenPose'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libopenpose.so.1.2.1: cannot open shared object file: No such file or directory
```

Knowing the location of `libopenpose.so.1.2.1`, I tried the following and got a different error...

```
$ cd $OPENPOSE_ROOT/build/src/openpose; ls libopenpose.so; python -c 'import PyOpenPose'
libopenpose.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/PyOpenPose/build/PyOpenPoseLib/PyOpenPose.so: undefined symbol: _ZN5boost6python7numeric5array19set_module_and_typeEPKcS4_
```

Any ideas on what's missing?
Thanks in advance!

**Comment by padeler** [comment]
Add the location of libopenpose to your LD_LIBRARY_PATH.
The library file must have the correct version on the name.

**Comment by joseph-zhong** [comment]
Hi @padeler thanks for the suggestion, I added it to the path, but I'm still getting the following error 

```
~$ python -c 'import PyOpenPose'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/local/PyOpenPose/build/PyOpenPoseLib/PyOpenPose.so: undefined symbol: _ZN5boost6python7numeric5array19set_module_and_typeEPKcS4_
```

It looks like something is wrong with Boost? Is there a particular version that is needed?
Thanks

**Comment by padeler** [comment]
Is the boost_python lib in your LD_LIBRARY_PATH?
Use ldd on the PyOpenPose.so to see the versions of the libs needed.

**Comment by HongDouE** [comment]
> 你的 LD_LIBRARY_PATH 中有 boost_python 库吗？ 在 PyOpenPose.so 上使用 ldd 查看所需库的版本。

您好，我也是出现了相同的问题

$ python -c 'import pydbow2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: ./pydbow2.so: undefined symbol: _ZN5boost6python7numeric5array19set_module_and_typeEPKcS4_


我尝试用ldd查看库版本

$ ldd pydbow2.so 
	linux-vdso.so.1 (0x00007ffddc7f8000)
	libDLib.so => /home/hongdou/fox/calc/TrainAndTest/ThirdParty/DBoW2/build/dependencies/install/lib/libDLib.so (0x00007f38b2bb6000)
	libDBoW2.so (0x00007f38b29a1000)
	libboost_python-py27.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1 (0x00007f38b2761000)
	libopencv_features2d.so.3.4 => /usr/local/lib/libopencv_features2d.so.3.4 (0x00007f38b2491000)
	libopencv_core.so.3.4 => /usr/local/lib/libopencv_core.so.3.4 (0x00007f38b1ec8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f38b1b3f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f38b17a1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f38b1589000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f38b1198000)
	libopencv_calib3d.so.3.4 => /usr/local/lib/libopencv_calib3d.so.3.4 (0x00007f38b0e07000)
	libopencv_highgui.so.3.4 => /usr/local/lib/libopencv_highgui.so.3.4 (0x00007f38b0bf1000)
	libopencv_imgcodecs.so.3.4 => /usr/local/lib/libopencv_imgcodecs.so.3.4 (0x00007f38b08a5000)
	libopencv_imgproc.so.3.4 => /usr/local/lib/libopencv_imgproc.so.3.4 (0x00007f38b0217000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f38afff8000)
	libopencv_flann.so.3.4 => /usr/local/lib/libopencv_flann.so.3.4 (0x00007f38afda0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f38afb9c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f38af994000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f38af777000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f38b3056000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f38af135000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f38aee80000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f38aeb63000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f38ae93f000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f38ae6eb000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f38ae3d4000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f38ae16c000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f38adf3a000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f38adcc2000)
	libIlmImf-2_2.so.22 => /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22 (0x00007f38ad7fe000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f38ad5fa000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f38ad3ed000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f38ad0b5000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f38aceaf000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f38acc89000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f38ac8ea000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f38ac6d4000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f38ac487000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f38ac242000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f38ac038000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f38abe35000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f38abc25000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f38aba1a000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f38ab810000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f38ab60d000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f38ab40a000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f38ab1f8000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f38aaf53000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f38aac9f000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f38aaa9c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f38aa874000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f38aa667000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f38aa45f000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f38aa1ee000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f38a9fc8000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f38a9dba000)
	libHalf.so.12 => /usr/lib/x86_64-linux-gnu/libHalf.so.12 (0x00007f38a9b77000)
	libIex-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12 (0x00007f38a9959000)
	libIlmThread-2_2.so.12 => /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12 (0x00007f38a9752000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f38a952a000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f38a9310000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f38a90bc000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f38a8e1e000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f38a8c15000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f38a89e3000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f38a87df000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f38a85d9000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f38a838c000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f38a815f000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f38a7f58000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f38a7d43000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f38a7b3c000)

我不太清楚具体哪里有问题？或者我应该从哪个方向修复错误？
感谢！
