### ISSUE TITLE
Strangely multiple Boost versions

### ISSUE THREAD

**Issue by HWiese1980** [FORTH-ModelBasedTracker/PyOpenPose#4]
Hello,

I'm trying to get the Python module running. It builds successful and installs into /usr/local/lib. That's fine by me. 

But I cannot import it. The import crashes with the following error message:

    ImportError: /usr/local/lib/PyOpenPose.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

which is probably due to the fact that PyOpenPose.so is linked against two different versions of Boost. The output of ldd (filtered by grep boost):

	libboost_python.so.1.64.0 => /usr/local/lib/libboost_python.so.1.64.0 (0x00007f0e55abf000)
	libboost_system.so.1.64.0 => /usr/local/lib/../lib/libboost_system.so.1.64.0 (0x00007f0e50f1f000)
	libboost_filesystem.so.1.64.0 => /usr/local/lib/../lib/libboost_filesystem.so.1.64.0 (0x00007f0e50d04000)
	libboost_thread.so.1.64.0 => /usr/local/lib/../lib/libboost_thread.so.1.64.0 (0x00007f0e4afe2000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007f0e275ec000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007f0e24505000)

Boost 1.58 is installed via `apt-get` in /usr/lib, Boost 1.64 is installed through the git clone/cmake/make chain in /usr/local/lib. 

If I remove Boost 1.64 completely I cannot import PyOpenPose because it (or rather libopenpose) complains about it missing... 

Any help would be greatly appreciated.

**Comment by padeler** [comment]
The import error looks like you've build with python3 and trying to load the lib using python2 (or vice versa). Check your cmake cache to make sure it found the correct python version.

Also you have to make sure that libboost_python.so is built for the python version you are using.

**Comment by djangogo** [comment]
@HWiese1980 you can try my installation guide.
https://github.com/djangogo/PyOpenPose

**Comment by HWiese1980** [comment]
@padeler Yepp, that's been the cause. Thanks for the hint. I've been able to solve it.

Solution for others encountering this issue and have, like me, multiple Python versions installed: in CMakeLists.txt explicitly define the PythonLibs (and PythonInterp) version you want to use. 

Change 

    find_package(PythonLibs REQUIRED) 

to 

    find_package(PythonLibs 2.7 REQUIRED) 

or whatever else your desired Python version might be.

**Comment by Jamboalv** [comment]
I used the above solution, but still get the error : 
"undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE"
@HWiese1980 @padeler @djangogo
