### ISSUE TITLE
Which parameter controls GPU memory consumption?

### ISSUE THREAD

**Issue by AlexLuya** [FORTH-ModelBasedTracker/PyOpenPose#42]
Hello,I am using PyOpenpose with below settings:
```
       self.poseSize = (656, 368)
        self.faceHandSize = (240, 240)
        self.outSize = (640, 480)
        self.modelType = "COCO"
        self.logLevel = 0
        self.downloadHeatmaps = False
        self.detectFace = False
        self.detectHands = False
```
Same python scripts+same settings as above,
under my laptop with a nvidia 1070 card,python wrapped openpose process consumed
1516MB GPU memory,
but under a server with nvidia 1080Ti card,openpose process consumed
7883MB GPU memory,
where does this big memory consumption comef from?Any parameter to specify GPU memory consumption?
(I have asked in openpose issue list:https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/526,but openpose guys said it isn't their problem)

**Comment by padeler** [comment]
This is not a PyOpenPose related issue. That said, try changing (reducing) the input resolution when initializing the PyOpenPose class and see how the memory consumption changes.

**Comment by joseph-zhong** [comment]
On that note, is there a parameter which determines which GPUId is utilized?

Thanks!
