### ISSUE TITLE
Disable background image

### ISSUE THREAD

**Issue by pedro-abreu** [FORTH-ModelBasedTracker/PyOpenPose#45]
I had to change a non-obvious true flag to false in OpenPoseWrapper and the pose renderer  (here `poseRenderer{poseModel, nullptr, 0.05, false, blendAlpha}`) to achieve this and it took me a while to find out. Could you make it less obscure for future users? Thank you.

**Comment by padeler** [comment]
You are right, this should be better documented.  I am just following the openpose API so most of the functions of the pose renderer are covered by their (openpose) documentation and forums.
