### ISSUE TITLE
Deleting op object

### ISSUE THREAD

**Issue by pedro-abreu** [FORTH-ModelBasedTracker/PyOpenPose#47]
How could I delete the OpenPose wrapper object and effectively free memory and then recreate another one? I need to parse different sized videos in a loop.

**Comment by padeler** [comment]
Hello, 

In the current version there is no way to do that (since i never needed it, i did not provision for it, sorry) you will have to right a proper destructor for OpenPoseWrapper to free all OP resources.

**Comment by paperManu** [comment]
Out of curiosity, which member of OpenPoseWrapper would need special handling in the desctructor. It seems to me that everything should be destroyed automatically as import members are inside a shared_ptr.
