### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by nanzhixiong** [FORTH-ModelBasedTracker/PyOpenPose#48]
[ 25%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o
[ 50%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/PyOpenPose.cpp.o
[ 75%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o
/home/nan/PyOpenPose-master/PyOpenPoseLib/opencv_expose.cpp:13:33: fatal error: numpy/ndarrayobject.h: No such file or directory
compilation terminated.
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:110: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o' failed
make[2]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by padeler** [comment]
It looks like the numpy headers are missing from your system. Have you installed numpy? which version of opencv and python are you building with?

**Comment by nanzhixiong** [comment]
yes, the numpy is installed.

thank you very much @christian-lanius!
