### ISSUE TITLE
Crash in OpLoop.py after "Entering main Loop.": corrupted double-linked list

### ISSUE THREAD

**Issue by HWiese1980** [FORTH-ModelBasedTracker/PyOpenPose#5]
Hi,

I've been able to initialize PyOpenPose now thanks to the advice from another issue here. Now I'm encountering a crash in the OpLoop.py example. It outputs a fairly long error message: https://pastebin.com/GLUJnX74

Thanks a lot for your help

**Comment by padeler** [comment]
This looks like an nvidia/gpu related issue and not PyOpenPose specific. 

Have you tried to run openpose with the same network dimensions (shown [here](https://github.com/FORTH-ModelBasedTracker/PyOpenPose/blob/master/scripts/OpLoop.py#L29))?

PyOpenPose initializes all three networks (body, hand, face) so if your GPU does not have enough RAM openpose will fail to start.

**Comment by HWiese1980** [comment]
It's a GTX 1060 so, yeah, might be VRAM related. I'll go check it out.

**Comment by padeler** [comment]
Did you resolve your issue? 

In case it is VRAM related this might be helpful:

In the master branch there is now an constructor argument that disables the hand and/or face networks. Disabling one of both nets will reduce the ram requirements.

**Comment by padeler** [comment]
I am closing this issue since it looks like it was resolved for @HWiese1980.

**Comment by HWiese1980** [comment]
Sorry, I haven't had time yet to check it, have been involved in other projects and vacation recently. I'll check it once I have the time. Hopefully soon...
