### ISSUE TITLE
Linking CXX shared library PyOpenPose.so error

### ISSUE THREAD

**Issue by hityang** [FORTH-ModelBasedTracker/PyOpenPose#50]
Dear sir:
   please look at this problem? Thanks.

[100%] Linking CXX shared library PyOpenPose.so
/usr/bin/ld: cannot find -lopenpose
/usr/bin/ld: cannot find -lcaffe
collect2: error: ld returned 1 exit status
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:177: recipe for target 'PyOpenPoseLib/PyOpenPose.so' failed
make[2]: *** [PyOpenPoseLib/PyOpenPose.so] Error 1
CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by veelion** [comment]
> /usr/bin/ld: cannot find -lopenpose
/usr/bin/ld: cannot find -lcaffe

Have you installed OpenPose and Caffe before you build PyOpenPose? You should install both of them firstly.

**Comment by hityang** [comment]
@veelion  Thanks, I installed the OpenPose again and solved the problem.
