### ISSUE TITLE
import PyOpenPose as OP ImportError: libopenpose.so.1.1.0: cannot open shared object file: No such file or directory error

### ISSUE THREAD

**Issue by hityang** [FORTH-ModelBasedTracker/PyOpenPose#51]
As the title shown, what is problem ?

**Comment by christian-lanius** [comment]
PyOpenPose is not on your pythonpath. Did building it work? If so, you have to add the path to the .so file to your search path for python modules.

**Comment by hityang** [comment]
@christian-lanius  Thanks. I solved this problem following the guide.
