### ISSUE TITLE
ModuleNotFoundError: No module named 'PyOpenPose'

### ISSUE THREAD

**Issue by GAVANXU** [FORTH-ModelBasedTracker/PyOpenPose#53]
Hello,@christian-lanius  @nkyriazis @padeler @oikonom  I have configured pyopenpose but found when I run scrpit demo, i find: ModuleNotFoundError: No module named 'PyOpenPose',Can you provide this module?

**Comment by padeler** [comment]
You have to build pyopenpose and openpose before running the python examples. Check the documentation for more details.
