### ISSUE TITLE
Use PyOpenPose in CPU only 

### ISSUE THREAD

**Issue by negarl** [FORTH-ModelBasedTracker/PyOpenPose#58]
I installed the CPU version of Openpose and now I want to install PyOpenPose to use it on python code. But I got this error : 

Install prefix is set to: /usr/local
Generating with build type: Release
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:49 (find_package)

What should I do? Do you know how to fix it or the PyOpenPose does not support the CPU version?

**Comment by lisa4930007** [comment]
I run the cmake on mac osx, however it can't be successfully compiled. I got the same problems as you. 
If I run on windows, there is still some problems happened. The screenshot are showed below.
![default](https://user-images.githubusercontent.com/14839962/44617701-34427280-a89a-11e8-8a00-5651a7c810e1.png)

Does anyone know how to do?

**Comment by JasOlean** [comment]
You should set OpenCV_Dir in your cmake. Where is the location of OpenCV installed?
