### ISSUE TITLE
where is pyopenpose

### ISSUE THREAD

**Issue by hushunda** [FORTH-ModelBasedTracker/PyOpenPose#59]
the  code   `import PyOpenPose as OP` in JustHand.py can't find PyOpenPose.
can you tell me where is pyopenpose

**Comment by padeler** [comment]
PyOpenPose is created when you build the library (follow the instructions on how to build it). Once you have the library built, make sure its location is in the PYTHONPATH.

**Comment by hushunda** [comment]
Thank you for your reply.

Is  the PyOpenPose  PyOpenPose.so instead of PyOpenPose.py?

**Comment by padeler** [comment]
PyOpenPose.so is the library you are looking for. Just add its location in your PYTHONPATH.

**Comment by JasOlean** [comment]
I set the PYTHONPATH in .bashrc file like this: export PYTHONPATH=/usr/local/lib/:$PYTHONPATH
But error is the same.
  File "JustHandNet.py", line 4, in <module>
    import PyOpenPose as OP
ImportError: No module named 'PyOpenPose'

**Comment by christian-lanius** [comment]
Can you try at the top of your script, before trying to import pyopenpose:
`
import sys
sys.path.insert(0, PATH_TO_PYOPENPOSE)
print(sys.path)
`
Replace PATH_TO_PYOPENPOSE with the correct path to the folder containing the pyopenpose.so file. Does the path to pyopenpose show up then?
