### ISSUE TITLE
PyOpenPose has no attribute OpenPose

### ISSUE THREAD

**Issue by ahmed-bensaad** [FORTH-ModelBasedTracker/PyOpenPose#62]
Hello,

I've got this error while trying to use PyOpenPose

`Traceback (most recent call last):
  File "generate_train_data.py", line 76, in <module>
    run()
  File "generate_train_data.py", line 15, in run
    op = OP.OpenPose((656, 368), (368, 368), (1280, 720), "COCO", OPENPOSE_ROOT + os.sep + "models" + os.sep, 0,
AttributeError: module 'PyOpenPose' has no attribute 'OpenPose'`

I use CUDA 9 on Ubuntu 18 and openpose is well installed.

**Comment by padeler** [comment]
Have you built PyOpenPose correctly?
When you do a 

```python
import PyOpenPose as OP
dir(OP)
```
You should get something like:
['OpenPose', '__doc__', '__file__', '__name__', '__package__']

**Comment by ahmed-bensaad** [comment]
yeah I got this 

`>>> import PyOpenPose as OP
>>> dir(OP)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`

**Comment by padeler** [comment]
Any progress on this building issue?

**Comment by ahmed-bensaad** [comment]
No :/ still looking for an answer
----- Mail d’origine -----
De: Panteleris Paschalis <notifications@github.com>
À: FORTH-ModelBasedTracker/PyOpenPose <PyOpenPose@noreply.github.com>
Cc: Ahmed Ben Saad <ahmed.bensaad@telecom-paristech.fr>, Author <author@noreply.github.com>
Envoyé: Mon, 01 Oct 2018 11:18:55 +0200 (CEST)
Objet: Re: [FORTH-ModelBasedTracker/PyOpenPose] PyOpenPose has no attribute OpenPose (#62)

Any progress on this building issue?

**Comment by BingWu1995** [comment]
This might because you haven't build the python API of openpose. You can try to rebuild openpose with the python API option on by editing the CMakeLists.txt ('option(BUILD_PYTHON "Build OpenPose python." ON)').
