### ISSUE TITLE
No module named PyOpenPose

### ISSUE THREAD

**Issue by JasOlean** [FORTH-ModelBasedTracker/PyOpenPose#63]
I installed PyOpenPose and I found library file PyOpenPose.so in PyOpenPoseLib file.
I add its lib location to the path. But when I run JustHandNet.py or JustFaceNet.py, I got this error.
How can I fix it? PyOpenPose.so path is home/username/PyOpenPose/build/PyOpenPoseLib/. 

Traceback (most recent call last):
  File "JustHandNet.py", line 5, in <module>
    import PyOpenPose as OP
ImportError: No module named PyOpenPose

**Comment by padeler** [comment]
You have to add the location of PyOpenPose.so into your PATHONPATH.

Also make sure you have built the library for the version of python you are using. I.e if you are using python3 you need to enable the python3 build from cmake before building.

**Comment by JasOlean** [comment]
Yes, I set the path for python2.7 in CMakeLists.txt. set(NUMPY_INCLUDE_DIRS "/usr/local/lib/python2.7/dist-packages/numpy/core/include"). Now I am using python2.7. Do I need to change python 3?

**Comment by JasOlean** [comment]
I made all of them when i install PyOpenPose. But I cannot fix still this error.
export PYTHONPATH=/home/username/PyOpenPose/build/PyOpenPoseLib/:$PYTHONPATH
Traceback (most recent call last):
  File "JustHandNet.py", line 5, in <module>
    import PyOpenPose as OP
ImportError: No module named 'PyOpenPose'

**Comment by padeler** [comment]
The reasons that might cause the error can be:
1. PyOpenPose.so is not built
2. PyOpenPose.so is built but not in the PYTHONPATH

is there a file named PyOpenPose.so in your build/PyOpenPoseLib folder?

**Comment by JasOlean** [comment]
Yes.  it is in build/PyOpenPoselib/PyOpenPose.so and also usr/local/lib/PyOpenPose.so when I make.

**Comment by JasOlean** [comment]
it is ok now. Thank you for your answer.
