### ISSUE TITLE
How to install with python3?

### ISSUE THREAD

**Issue by JasOlean** [FORTH-ModelBasedTracker/PyOpenPose#64]
when I install with python3, I got this error. My default python is 2.7.12. but I already also installed python 3.5.2. How can I install?

~/PyOpenPose/build$ cmake -WITH_PYTHON=3 ..
Install prefix is set to: /usr/local
Generating with build type: Release
-- Could NOT find Boost
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   python-py35
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PythonLibs: Found unsuitable version "2.7.12", but required
  is exact version "3" (found /usr/lib/x86_64-linux-gnu/libpython2.7.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPythonLibs.cmake:265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:72 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by padeler** [comment]
Use the WITH_PYTHON3 switch

**Comment by JasOlean** [comment]
Yes, I checked WITH_PYTHON3 in cmake-gui.  I got this error.

**Comment by padeler** [comment]
In the command line you posted above the "-WITH_PYTHON=3" which is probably the issue.

**Comment by oikonom** [comment]
Ρε, δεν έχει καταλάβει, είμαι σίγουρος

**Comment by JasOlean** [comment]
It is just typing error. I checked WITH_PYTHON3 in cmake-gui but it is not ok. 
So, I used this command!!! Now it is ok. 
cmake ..  -DPYTHON_INCLUDE_DIR=/usr/include/python3.5 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5.so
Thank you
