### ISSUE TITLE
handBB value is fixed or not?

### ISSUE THREAD

**Issue by JasOlean** [FORTH-ModelBasedTracker/PyOpenPose#65]
initial handBB value is fixed or could I change dynamically this value? How can I change?
Please guide me.

**Comment by padeler** [comment]
handBB is a parameter you supply to the [detectHands](https://github.com/FORTH-ModelBasedTracker/PyOpenPose/blob/master/scripts/JustHandNet.py#L73) method. You can set it yourself.
