### ISSUE TITLE
Error Makefile

### ISSUE THREAD

**Issue by vipermu** [FORTH-ModelBasedTracker/PyOpenPose#66]
Hello!

(Sorry for my lack of knowledge in the field, it's the first time that I try to configure a wrapper from cpp to python)

I've built openpose apparently correctly in MacOS 10.12.6 (using Cmake) but when I try to run the "make install" commad I get the following error:

make: *** No rule to make target `install'.  Stop.

I found on Internet that "make -f Makefile" or just "make" should do the same stuff. This seems to start configurating 'openpose_caffe', but I get the following errors during the configuration:

make[2]: *** [caffe/src/openpose_caffe-stamp/openpose_caffe-configure] Error 1
make[1]: *** [CMakeFiles/openpose_caffe.dir/all] Error 2
make: *** [all] Error 2

Seems like two files inside caffe are missing. I'm not used to work with cpp and I never used caffe Framework, so I don't know why I don't have this files...

Any help is welcome :)
Thanks!

**Comment by padeler** [comment]
First you need to build openpose. Follow the instructions on the openpose website to do that. Once you have openpose compiled and you can run the examples you can build PyOpenPose.
First set the OPENPOSE_ROOT env variable to point to the openpose install. This way cmake will find it and create the Makefile.
