### ISSUE TITLE
Make Error:  fatal error: openpose/core/headers.hpp: No such file or directory  

### ISSUE THREAD

**Issue by switchhh** [FORTH-ModelBasedTracker/PyOpenPose#68]
When I finish cmake,and run make in build,I got this error:

PyOpenPose/PyOpenPoseLib/OpenPoseWrapper.cpp:9:37: fatal error: openpose/core/headers.hpp: No such file or directory
 #include <openpose/core/headers.hpp>
                                     ^
compilation terminated.
make[2]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o] Error 1
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
make: *** [all] Error 2

How can I fix this? 
Is there anything I didn't finish?

**Comment by padeler** [comment]
Is OPENPOSE_ROOT set correctly to point to the install folder. The install folder will contain an include dir with the missing header file you see in the error.

**Comment by Rainweic** [comment]
> Is OPENPOSE_ROOT set correctly to point to the install folder. The install folder will contain an include dir with the missing header file you see in the error.

I also meet this problem, I git clone the OpenPose in ~, so I "export OPENPOSE_ROOT=/home/myname/openpose”, is it right? Please help me, thanks.

this is the error:

`/home/bhrgzn/PyOpenPose/PyOpenPoseLib/OpenPoseWrapper.cpp:9:37: fatal error: openpose/core/headers.hpp: 没有那个文件或目录
compilation terminated.
PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:62: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o' failed
make[2]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed
make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by padeler** [comment]
OPENPOSE_ROOT should point to the installation directory of openpose not to the source root. When you build openpose with cmake you can define an installation directory to which the "make install" target will copy all headers and binaries.

Please note that the example scripts of PyOpenPose look into $OPENPOSE_ROOT/models for the openpose weight files so you should make sure the models are in that location or change the example scripts accordingly.

**Comment by uuhh25** [comment]
> > Is OPENPOSE_ROOT set correctly to point to the install folder. The install folder will contain an include dir with the missing header file you see in the error.
> 
> I also meet this problem, I git clone the OpenPose in ~, so I "export OPENPOSE_ROOT=/home/myname/openpose”, is it right? Please help me, thanks.
> 
> this is the error:
> 
> `/home/bhrgzn/PyOpenPose/PyOpenPoseLib/OpenPoseWrapper.cpp:9:37: fatal error: openpose/core/headers.hpp: 没有那个文件或目录 compilation terminated. PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/build.make:62: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o' failed make[2]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/OpenPoseWrapper.cpp.o] Error 1 make[2]: *** 正在等待未完成的任务.... CMakeFiles/Makefile2:117: recipe for target 'PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all' failed make[1]: *** [PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/all] Error 2 Makefile:127: recipe for target 'all' failed make: *** [all] Error 2`

If you have handled it and could you tell me how to solve this error?Please help me!!Thanks! @switchhh@Rainweic
