### ISSUE TITLE
How can find the distance between wrist joint location to fingertip.

### ISSUE THREAD

**Issue by sainisanjay** [FORTH-ModelBasedTracker/PyOpenPose#7]
@padeler I want to find the distance between wrist joint location to fingertip. For example, left wrist joint location to little fingertip. Any idea how to do this..... Help needed... Thanks

**Comment by padeler** [comment]
I am assuming you are talking about the length of the 2d path created by the joint segments from the wrist joint on the pinky tip joint in which case you can just sum all the individual joints segment lengths.

This is not a PyOpenPose related issue, it is more of a general programming question, so I am closing it.
