### ISSUE TITLE
Trying to run PyOpenPose on Google Colaboratory

### ISSUE THREAD

**Issue by choubeyaakash77** [FORTH-ModelBasedTracker/PyOpenPose#72]
I'm trying to run it on Google Colab as I don't have a GPU.
I was able install CUDA, CuDNN, OpenCV3 and most other required libraries. OpenPose was build successfully. 
At the moment, I'm stuck with installing boost.
https://stackoverflow.com/questions/53383267/running-pyopenpose-on-google-colab

The exact error is -
```
cmake: /usr/local/lib/libcurl.so.4: no version information available 
(required by cmake)
Install prefix is set to: /usr/local
Generating with build type: Release
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Boost version: 1.65.1
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1626     (message):
  No header defined for python2; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:61 (find_package)

CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Could not find the following Boost libraries:

      boost_python2

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or     BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:61 (find_package)


-- The following REQUIRED packages have been found:
 * Threads
 * CUDA
 * OpenCV (required version >= 3)
 * PythonLibs (required version == 2.7)

-- The following OPTIONAL packages have not been found:
 * Doxygen

-- The following REQUIRED packages have not been found:
 * Boost

-- Configuring incomplete, errors occurred!
See also "/content/PyOpenPose/build/CMakeFiles/CMakeOutput.log".
See also "/content/PyOpenPose/build/CMakeFiles/CMakeError.log".

```

My runtime environment is Python3, why do I need boost_python2? Even if I do, how should I get it?

**Comment by padeler** [comment]
if you have boost-python for python3 installed, you should turn the flag WITH_PYTHON3 in the CMakeLists.txt file to TRUE. Openpose runs fine on colab so PyOpenPose should work fine as well although i have never tested it.

**Comment by choubeyaakash77** [comment]
Thanks, this worked but I get another error...
`!cmake -D WITH_PYTHON3=True ..`
OUTPUT - 
```
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
Install prefix is set to: /usr/local
Generating with build type: Release
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Boost version: 1.63.0
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1626 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)


-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   system
--   python3
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs: Found unsuitable version "2.7.15rc1", but
  required is exact version "3" (found
  /usr/lib/x86_64-linux-gnu/libpython2.7.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:72 (find_package)


-- Configuring incomplete, errors occurred!
See also "/content/PyOpenPose/build/CMakeFiles/CMakeOutput.log".
See also "/content/PyOpenPose/build/CMakeFiles/CMakeError.log".
```

The directory `usr/lib/x86_64-linux-gnu/` contains

> libpython2.7.a
> libpython2.7.so
> libpython2.7.so.1
> libpython2.7.so.1.0
> libpython3.6m.a
> libpython3.6m.so
> libpython3.6m.so.1
> libpython3.6m.so.1.0

and `usr/bin` has these available

> dh_python2
> dh_python3
> python
> python-config
> python2
> python2-config
> python2.7
> python2.7-config
> python3
> python3-config
> python3.6
> python3.6-config
> python3.6m
> python3.6m-config
> python3m
> python3m-config
> x86_64-linux-gnu-python-config
> x86_64-linux-gnu-python2.7-config
> x86_64-linux-gnu-python3-config
> x86_64-linux-gnu-python3.6-config
> x86_64-linux-gnu-python3.6m-config
> x86_64-linux-gnu-python3m-config


Should I be touching the CMakeLists file and edit `find_package(PythonLibs 3 EXACT REQUIRED)`? 
What should I do here?

**Comment by padeler** [comment]
Yes, since you build on colaboratory which is not a standard setup, you should adapt CMakeLists file to fit your requirements. I.e. Remove the EXACT from the find_package command, or set the boost version to the one colaboratory already has.
