### ISSUE TITLE
OpenCV_FOUND is set to False.

### ISSUE THREAD

**Issue by YongWookHa** [FORTH-ModelBasedTracker/PyOpenPose#75]
```
>>cmake ..
Install prefix is set to: C:/Program Files (x86)/PyOpenPose
Generating with build type:
-- OpenCV ARCH: x86
-- OpenCV RUNTIME: vc12
-- OpenCV STATIC: ON
CMake Warning at C:/Users/YongWook/AppData/Local/Continuum/anaconda3/envs/pose2pose/Library/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:49 (find_package)


CMake Error at CMakeLists.txt:49 (find_package):
  Found package configuration file:

    C:/Users/YongWook/AppData/Local/Continuum/anaconda3/envs/pose2pose/Library/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.


-- Configuring incomplete, errors occurred!
See also "C:/Users/YongWook/Documents/GitHub/PyOpenPose/build/CMakeFiles/CMakeOutput.log".
```

After installed opencv3 with command of `conda install -c menpo opencv3`, I tried to cmake in the build folder. The installed cv2's version is 3.1.0.

But `OpenCV_FOUND` is set to `FALSE` though the package configuration file has been found. They say it has no binaries compatible with the configuration.

Is there any way to solve this problem except pointing the OpenCV_DIR to CMAKE?

**Comment by padeler** [comment]
You need the opencv dev package because the C++ part of PyOpenPose uses the opencv headers.

As far as I know the conda package only contains the dlls + python wrappers. Get the windows dev package of opencv from the official opencv site.

**Comment by YongWookHa** [comment]
Thank you for the answer. I decided to use opencv and other libs which are provided by openpose. 
Anyway, I needed to use cmake which is intalled by `conda install`.
