### ISSUE TITLE
python3 can not use is Boost 　version  problem?

### ISSUE THREAD

**Issue by wakingking77** [FORTH-ModelBasedTracker/PyOpenPose#76]
I want use my python3 ,but it alway remaid me Boost is not right.And I use all of ways to use python3 in github,they all failed.
so I thought it may be  Boost 　version  problem.
My  Boost 　version   is  1.58, and  Pyopenpose required is 1.63.
It is that problem? 
"Ubuntu 16.04    python3.5.2   + 2.7    Boost1.58"

**Comment by padeler** [comment]
Boost 1.58 works fine with PyOpenPose. Can you be a bit more specific about the problem?

**Comment by wakingking77** [comment]
> Boost 1.58 works fine with PyOpenPose. Can you be a bit more specific about the problem?

I want to use python3. 
And I cmake PyOpenPose with cmake-gui or  oder,but they all failed.
****cmake-gui remaided:**** 
```
Could NOT find Boost
Boost version: 1.58.0
Found the following Boost libraries:
  system
  python-py35
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PythonLibs: Found unsuitable version "2.7.12", but required
  is exact version "3" (found /usr/lib/x86_64-linux-gnu/libpython2.7.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindPythonLibs.cmake:265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:72 (find_package)
```
**Oder is :**　
`sudo cmake .. -WITH_PYTHON=3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so`
**Failed remaided:**

**Comment by wakingking77** [comment]
> Boost 1.58 works fine with PyOpenPose. Can you be a bit more specific about the problem?

Thank your answer  very much ! I know it is not reason of  Boost.

Now! it can work finally!  I don't konw why,but it can use python3!!!!!
when I am answering your quanstion more specificly,I run the bug medthon of Cmake-gui and Oder.
**I only do two step:
1.use cmake-gui:choose the python3. and it reminded failed!
2.use this oder to cmake:` sudo cmake .. -WITH_PYTHON=3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so`**
So it can work!  
so soon!
so easy!
and so amazing!
And I don't know why?!
