### ISSUE TITLE
ImportError:  libopenpose.so.1.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HuiminHe** [FORTH-ModelBasedTracker/PyOpenPose#8]
Hi, I am running PyOpenPose on AWS EC2 ubuntu14.0.4 and system default python2.7.6 I run `make` and `sudo make install ` fine but I cannot import PyOpenPose in python. libopenpose.so is installed in `/usr/local/lib.`  there is another file with the same name in `/home/ubuntu/PyOpenPose/build/PyOpenPoseLib.`
if I add the first one into `$PYTHONPATH`, it returns:

`>>> import PyOpenPose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libopenpose.so.1.0.2: cannot open shared object file: No such file or directory
`

Or if i add the second on into $PYTHONPATH:
`>>> import PyOpenPose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ubuntu/PyOpenPose/build/PyOpenPoseLib/PyOpenPose.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
`
Which according to some [Discussion](https://groups.google.com/forum/#!topic/caffe-users/flffQCt_YHQ) on Google is related to libboost.

Any suggestions?

**Comment by padeler** [comment]
Hi,

You just need to put the location of  PyOpenPose.so in the PYTHONPATH.
If you build openpose with "make distribute" it will copy all the required libs into a folder named $OPENPOSE_ROOT/distribute

Once you have open pose built and the above two environment variables set you should be able to import PyOpenPose in your scripts.

ps: note that PyOpenPose requires opencv3.x 

I hope this helps

**Comment by HuiminHe** [comment]
Thanks for your reply! 
I have set $OPENPOSE_ROOT, append /usr/local/lib into $PYTHONPATH and installed OpenCV3.3.0. It seems to be the problem of lib_boost on my server.

Although I have not figured this out, I have found another way to solve my solution.

**Comment by derekwong66** [comment]
@HuiminHe I met the same problem. How do you fix it?

**Comment by HuiminHe** [comment]
@derekwong66 I didn't. I was motivated to use PyOpenPose because OpenPose starts a GUI which cause an error on Linux server. I find a way to turn it off and thus no longer need PyOpenPose in my case.

**Comment by ajdroid** [comment]
How did you turn off the GUI? @HuiminHe

**Comment by HuiminHe** [comment]
I modified and compile openpose/examples/openpose/openpose.cpp. There are flags likes no_display, no_gui_verbose. Turning them off solved my problem.

**Comment by HuiminHe** [comment]
@ajdroid I modified and compile openpose/examples/openpose/openpose.cpp. There are flags likes no_display, no_gui_verbose. Turning them off solved my problem.
