### ISSUE TITLE
did not match C++ signature

### ISSUE THREAD

**Issue by highway007** [FORTH-ModelBasedTracker/PyOpenPose#80]
When I run the JustFaceNet.py ,I got this error:
**Traceback (most recent call last):
  File "JustFaceNet.py", line 106, in <module>
    run()
  File "JustFaceNet.py", line 53, in run
    download_heatmaps, OP.OpenPose.ScaleMode.ZeroToOne, with_face, with_hands)
Boost.Python.ArgumentError: Python argument types in
    OpenPose.__init__(OpenPose, tuple, tuple, tuple, str, str, int, bool, ScaleMode, bool, bool)
did not match C++ signature:
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode, bool, bool, int)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode, bool, bool)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode, bool)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, OpenPoseWrapper::ScaleMode)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)
    __init__(_object*, cv::Size_<int>, cv::Size_<int>, cv::Size_<int>)
    __init__(_object*)
    __init__(_object*)
**

**Comment by highway007** [comment]
I think something wrong with boost,but there is only one version of boost:
ldd /home/unimation/PyOpenPose/build/PyOpenPoseLib/PyOpenPose.so |grep boost
**	libboost_python36.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_python36.so.1.67.0 (0x00007f97ba954000)
	libboost_system.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.67.0 (0x00007f97afb75000)
	libboost_filesystem.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.67.0 (0x00007f97afb58000)
	libboost_thread.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.67.0 (0x00007f97af543000)
	libboost_python27.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_python27.so.1.67.0 (0x00007f979b691000)
**
ldd /home/unimation/PyOpenPose/build/PyOpenPoseLib/PyOpenPose.so |grep python
**	libboost_python36.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_python36.so.1.67.0 (0x00007f202f319000)
	libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007f202ee6b000)
	libboost_python27.so.1.67.0 => /usr/lib/x86_64-linux-gnu/libboost_python27.so.1.67.0 (0x00007f2010056000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f200fcea000)
**
I'm confused about this error ,could you plz help me?

**Comment by padeler** [comment]
Hello,
It looks like the issue is that you have mixed boost-python versions for python27 and python36 (check the versions in the ldd output you sent me). 

br,

**Comment by highway007** [comment]
@padeler Thx,I will reinstall boost and build pyopenpose again.
