### ISSUE TITLE
cmake error unable to find the request boost libraries

### ISSUE THREAD

**Issue by 517030910405** [FORTH-ModelBasedTracker/PyOpenPose#82]
Excuse me
When I run 

> make ..

It shows: 

> CMake Error at /home/name/.conda/envs/hand_torch0.3/share/cmake-3.14/Modules/FindBoost.cmake:2132 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.66.0
> 
>   Boost include path: /usr/local/include
> 
>   Could not find the following Boost libraries:
> 
>           boost_python-py27
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
> Call Stack (most recent call first):
>   CMakeLists.txt:67 (find_package)
> 
> 
> CMake Error at CMakeLists.txt:89 (message):
>   Environment variable OPENPOSE_ROOT is not set.  Please set and point to
>   openpose installation folder
> 

And I dont know what to do. Thank you for viewing my question.

**Comment by 517030910405** [comment]
And I dont know what to do. Thank You for viewing my question.

**Comment by 517030910405** [comment]
`

**Comment by padeler** [comment]
You need the boost_python library.  Either install it from the standard ubuntu repositories or build it.
Note that If you are building boost the name of the library will be boost_python (without the -py27 suffix). You will have to update the cmake scripts accordingly.
