### ISSUE TITLE
can it used for 3D human pose estimation only with one youtube video？

### ISSUE THREAD

**Issue by andiconda** [FORTH-ModelBasedTracker/PyOpenPose#83]
can it used for 3D human pose estimation only with one youtube video？
when my video is got with one camera.

**Comment by padeler** [comment]
This project a python wrapper for the [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose)  library. Openpose only detects 2D keypoints (i.e. joints) on human from monocular (single camera) rgb input.
